repos:
  - repo: local
    hooks:
      - id: phpstan
        name: PHPStan (Static Analysis)
        entry: sh -c 'mkdir -p code_test && [ ! -f "./code_test/phpstan" ] && (cd code_test && wget https://github.com/phpstan/phpstan/releases/latest/download/phpstan.phar -O phpstan && chmod +x phpstan); ./code_test/phpstan analyse src/ --level=max 2>&1 | tee -a /var/log/pre-commit.log'
        language: system
        types: [php]

      - id: phpunit
        name: Run PHPUnit
        entry: sh -c 'mkdir -p code_test && [ ! -f "./code_test/phpunit" ] && (cd code_test && wget https://phar.phpunit.de/phpunit-7.phar -O phpunit && chmod +x phpunit); ./code_test/phpunit 2>&1 | tee -a /var/log/pre-commit.log'
        language: system
        types: [php]

      - id: phpcs
        name: PHP CodeSniffer
        entry: sh -c 'mkdir -p code_test && [ ! -f "./code_test/phpcs" ] && (cd code_test && wget https://github.com/squizlabs/PHP_CodeSniffer/releases/latest/download/phpcs.phar -O phpcs && chmod +x phpcs); ./code_test/phpcs --standard=PSR12 src/ 2>&1 | tee -a /var/log/pre-commit.log'
        language: system
        types: [php]

      - id: psalm
        name: Psalm (Static Analysis)
        entry: sh -c 'mkdir -p code_test && [ ! -f "./code_test/psalm" ] && (cd code_test && wget https://github.com/vimeo/psalm/releases/latest/download/psalm.phar -O psalm && chmod +x psalm); [ ! -f "psalm.xml" ] && ./code_test/psalm --init || true; ./code_test/psalm --show-info=false 2>&1 | tee -a /var/log/pre-commit.log'
        language: system
        types: [php]

      - id: rector
        name: Rector (Refactoring)
        entry: sh -c 'mkdir -p code_test && [ ! -f "./code_test/rector" ] && (cd code_test && wget https://github.com/rectorphp/rector/releases/latest/download/rector.phar -O rector && chmod +x rector); ./code_test/rector process src/ 2>&1 | tee -a /var/log/pre-commit.log'
        language: system
        types: [php]

      - id: security-checker
        name: PHP Security Checker
        entry: sh -c 'mkdir -p code_test && [ ! -f "./code_test/local-php-security-checker" ] && (cd code_test && wget https://github.com/fabpot/local-php-security-checker/releases/latest/download/local-php-security-checker_linux_amd64 -O local-php-security-checker && chmod +x local-php-security-checker); [ ! -f "composer.lock" ] && composer install --no-scripts || true; ./code_test/local-php-security-checker 2>&1 | tee -a /var/log/pre-commit.log'
        language: system
        types: [php]

      - id: exakat
        name: Exakat (Security + Compatibility)
        entry: sh -c 'mkdir -p code_test && [ ! -f "./code_test/exakat.phar" ] && (cd code_test && wget https://github.com/exakat/exakat/releases/latest/download/exakat.phar -O exakat.phar && chmod +x exakat.phar); ./code_test/exakat.phar -p project -R 2>&1 | tee -a /var/log/pre-commit.log'
        language: system
        types: [php]

